Traceback (most recent call last):
  File "D:\Masters\Projects\thesis\cognitive-PPO\playground.py", line 288, in <module>
    action, logprob, _, value = agent.get_action_and_value(next_obs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Masters\Projects\thesis\cognitive-PPO\playground.py", line 76, in get_action_and_value
    probs = Categorical(logits)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hxri\miniconda3\envs\cogppo\Lib\site-packages\torch\distributions\categorical.py", line 66, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "C:\Users\hxri\miniconda3\envs\cogppo\Lib\site-packages\torch\distributions\distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (4, 7)) of distribution Categorical(probs: torch.Size([4, 7])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[ 0.6619,  1.6165, -3.2121,  0.4620,  0.9774, -2.2563,  2.7505],
        [ 0.0275,  0.8573, -1.2822,  0.5234,  0.6241, -1.1646,  1.4146],
        [ 0.6707,  2.2885, -4.9124,  0.8759,  1.4640, -3.5440,  4.1574],
        [ 0.6707,  2.2885, -4.9124,  0.8759,  1.4640, -3.5440,  4.1574]])